### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by redpanda3** [OpenXiangShan/fudian#12]
![QQ截图20220321165154](https://user-images.githubusercontent.com/28216801/159229661-1aab0267-e1fb-4067-8524-1c8bc2690bc2.png)
Hi, there are some errors when I tried 'make all_tests', any solution?

**Comment by lqr8** [comment]
How did you build testfloat?
Try using `make berkeley-testfloat-3/build/Linux-x86_64-GCC/testfloat_gen`

**Comment by redpanda3** [comment]
It works now. Thank you
