### ISSUE TITLE
make run errors

### ISSUE THREAD

**Issue by rvcoresjw** [OpenXiangShan/fudian#16]
在pipeline分支上，根据README进行操作，执行到 make all_tests 这一步会报错。
错误如下：
<img width="1342" alt="9df985b93197f7715be7b9c01f053a7" src="https://user-images.githubusercontent.com/89454015/228424849-5aa82496-d741-4b6b-9898-f644b602aeba.png">

**Comment by poemonsense** [comment]
Fixed by #19
