### ISSUE TITLE
Issue running test

### ISSUE THREAD

**Issue by jaschengWoodpeckerx** [OpenXiangShan/fudian#20]
Hi, we are trying to reproduce some of the floating-point bugs in Nan Hu to verify our internal product.
We checkout the nanhu design at: c067e65501c4d8dd61f010176acd9161272b9c92.

However, as I'm now trying to run fudian (43474be), I'm running into errors like below:

[info] compiling 17 Scala sources to /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/out/fudian/compile/dest/classes ...
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:35:58: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val adder_in_sig_b = Mux(effSub, (~adder_in_sig_b_raw).asUInt(), adder_in_sig_b_raw) + effSub
[error]                                                          ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:103:52: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val b_sig = (Cat(b.sig, 0.U(1.W)) >> need_shift).asUInt()
[error]                                                    ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:113:36: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val lza_str_zero = !Cat(lza_str).orR()
[error]                                    ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:120:7: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]     ).asUInt())(precision , 0)
[error]       ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:139:61: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]     case i           => lza_str.head(precision + 1 - i - 1).orR()
[error]                                                             ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FADD.scala:557:40: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val need_swap = exp_diff_a_b.head(1).asBool() || b_flags.overflow
[error]                                        ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FCMP.scala:27:49: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val uint_less = fp_a.sign ^ a_minus_b.head(1).asBool()
[error]                                                 ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FDIV.scala:318:19: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val sticky = (r.orR()) || (needShiftReg && qFinal(0)) // if non-zero remainder( which must be positive), we
[error]                   ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FDIV.scala:319:43: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val round = Mux(needShiftReg, qFinal(1).asBool(), qFinal(0).asBool)
[error]                                           ^
[error] /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/src/main/scala/fudian/FMUL.scala:78:43: overloaded method value apply with alternatives:
[error]   (x: BigInt,y: BigInt)chisel3.UInt <and>
[error]   (x: Int,y: Int)chisel3.UInt <and>
[error]   (x: chisel3.UInt)chisel3.Bool <and>
[error]   (x: Int)chisel3.Bool <and>
[error]   (x: BigInt)chisel3.Bool
[error]  cannot be applied to ()
[error]   val prod_exp_uf = shift_lim_sub.head(1).asBool()
[error]                                           ^
[error] 45 errors found

Am I missing something?

**Comment by poemonsense** [comment]
We fixed the Chisel version of fudian repo in #17. It should work as expected now.

**Comment by jaschengWoodpeckerx** [comment]
Thanks. I'm able to do the same edits myself and I can compile.
However, this issue emerges:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at fudian.Generator$.$anonfun$getModuleGen$2(Generator.scala:29)
        at chisel3.Module$.do_apply(Module.scala:53)
        at chisel3.stage.phases.Elaborate.$anonfun$transform$2(Elaborate.scala:40)
        at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:834)
...
Caused by: chisel3.package$ChiselException: The Chisel compiler plugin is now required for compiling Chisel code. Please see https://github.com/chipsalliance/chisel3#build-your-own-chisel-projects.
        at chisel3.internal.throwException$.apply(Error.scala:93)
        at chisel3.Bundle._elementsImpl(Aggregate.scala:1449)
        at chisel3.Bundle.elements$lzycompute(Aggregate.scala:1394)
        at chisel3.Bundle.elements(Aggregate.scala:1394)
        at chisel3.Record._elements$lzycompute(Aggregate.scala:1213)
        at chisel3.Record._elements(Aggregate.scala:1212)
        at chisel3.Record.elementsIterator(Aggregate.scala:1247)
        at chisel3.Record._minId$lzycompute(Aggregate.scala:1278)
        at chisel3.Record._minId(Aggregate.scala:1277)
        at chisel3.Data.mustClone(Data.scala:377)
        at chisel3.IO$.apply(IO.scala:33)
        at chisel3.experimental.BaseModule.IO(Module.scala:566)
        at fudian.FADD.$anonfun$io$20(FADD.scala:751)
        at chisel3.experimental.prefix$.apply(prefix.scala:50)
        at fudian.FADD.$anonfun$io$19(FADD.scala:751)
        at chisel3.internal.plugin.package$.autoNameRecursively(package.scala:33)
        at fudian.FADD.<init>(FADD.scala:751)
        ... 64 more
1 targets failed
fudian.runMain subprocess failed
make: *** [Makefile:86: /mnt/efs/home/jascheng/xs-env/XiangShan/fudian/build/FADD_32/FADD.v] Error 1

I have prepared the environment as outlined in xs-env setup-tools.sh
Also, I did not touch the build.sc under fudian.
